Add reverse proxy management functionality with menu integration

diff --git a/src/mytool b/src/mytool
--- a/src/mytool
+++ b/src/mytool
@@ -3,5 +3,392 @@
 # ===== Sources ===================================================================================
 
 source "./lib/ansi.sh"
+source "./lib/settings.sh"
+source "./lib/menu.sh"
+
+# ===== Utils =====================================================================================
+
+# Function to wait for a key press
+wait_for_key() {
+   echo
+   echo -e "${DIM}Press any key to continue...${RESET}"
+   read -rsn1
+}
+
+# Display the information of a specific settings key
+settings_display_key_info() {
+   local key=$1
+   local value=${settings[$key]}
+   local default_value=${default_settings[$key]}
+
+   echo -e "Key: ${key}"
+   echo -e "Current value: ${value}"
+   echo -e "Default value: ${default_value}"
+}
+
+# ===== Reverse Proxy Manager =====================================================================
+
+declare -A domains_and_ports
+
+# Utility function to load domains and ports into an associative array
+reverse_proxy_load_configs() {
+   # Check if the Nginx config directory exists
+   if [ ! -d "${settings["NGINX_CONFIG_DIR"]}" ]; then
+      echo -e "${RED}Nginx configuration directory does not exist!${RESET}"
+      return
+   fi
+
+   # Loop through each .conf file in the Nginx config directory
+   for config_file in "${settings["NGINX_CONFIG_DIR"]}"/*.conf; do
+      if [ -f "$config_file" ]; then
+         # Extract domain and port using grep and awk or sed (assuming proxy_pass is set)
+         domain=$(grep -oP 'server_name\s+\K[^\s;]+' "$config_file")                          # Extract the domain
+         port=$(grep -oP 'proxy_pass\s+http://(127.0.0.1|localhost):\K[0-9]+' "$config_file") # Extract the port number
+
+         # Check if both domain and port are valid
+         if [[ -n "$domain" && -n "$port" ]]; then
+            domains_and_ports["$domain"]="$port" # Store in the array
+            echo -e "${GREEN}Loaded reverse proxy configuration: ${WHITE}${domain} -> ${DIM}localhost:${port}${RESET}"
+         else
+            echo -e "${RED}Invalid configuration file: $config_file${RESET}"
+         fi
+      fi
+   done
+}
+
+# Function to save a reverse proxy configuration to its own Nginx configuration file
+reverse_proxy_save_config() {
+   local domain=$1
+   local port=$2
+   local config_file="${settings["NGINX_CONFIG_DIR"]}/${domain}.conf"
+
+   # Write the Nginx configuration to the file
+   echo "server {" >"$config_file"
+   echo "    listen 80;" >>"$config_file"
+   echo "    server_name $domain;" >>"$config_file"
+   echo "" >>"$config_file"
+   echo "    location / {" >>"$config_file"
+   echo "        proxy_pass http://localhost:$port;" >>"$config_file"
+   echo "        proxy_set_header Host \$host;" >>"$config_file"
+   echo "        proxy_set_header X-Real-IP \$remote_addr;" >>"$config_file"
+   echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;" >>"$config_file"
+   echo "        proxy_set_header X-Forwarded-Proto \$scheme;" >>"$config_file"
+   echo "    }" >>"$config_file"
+   echo "}" >>"$config_file"
+}
+
+# ===== Tasks =====================================================================================
+
+# Add a new reverse proxy configuration
+task_add_reverse_proxy() {
+   clear
+
+   echo -e "${DIM}Add a new reverse proxy configuration${RESET}"
+
+   # Ask for domain
+   echo
+   read -p -r "Enter domain: " domain
+
+   # Check if the domain already exists
+   if [ -n "${domains_and_ports[$domain]}" ]; then
+      echo
+      echo -e "${RED}Domain already exists.${RESET}"
+      wait_for_key
+      return
+   fi
+
+   # Ask for port
+   read -p -r "Enter port: " port
+
+   # Validate the port number
+   if ! [[ "$port" =~ ^[0-9]+$ ]] || [ "$port" -lt 1 ] || [ "$port" -gt 65535 ]; then
+      echo -e "${RED}Invalid port: ${port}. Please enter a port number between 1 and 65535.${RESET}"
+      wait_for_key
+      return
+   fi
+   echo
+
+   # Save the reverse proxy configuration
+   echo -e "${DIM}Saving reverse proxy configuration...${RESET}"
+   reverse_proxy_save_config "$domain" "$port"
+
+   # Reload Nginx
+   echo -e "${DIM}Reloading Nginx...${RESET}"
+   systemctl reload nginx
+
+   # Reload the reverse proxy configurations
+   echo -e "${DIM}Reloading reverse proxy configurations...${RESET}"
+   reverse_proxy_load_configs &>/dev/null
+
+   # Rebuild the menu
+   echo -e "${DIM}Updating menu...${RESET}"
+   update_menu "reverse_proxy"
+
+   echo
+   echo -e "${GREEN}Reverse proxy configuration added.${RESET}"
+
+   wait_for_key
+}
+
+task_modify_reverse_proxy() {
+   local domain=$1
+   local port=${domains_and_ports[$domain]}
+
+   clear
+
+   echo -e "${DIM}Modify reverse proxy configuration for ${domain}${RESET}"
+
+   # Ask for new port
+   echo
+   read -p -r "Enter port [${port}]: " new_port
+   new_port=${new_port:-$port}
+
+   # Validate the port number
+   if ! [[ "$new_port" =~ ^[0-9]+$ ]] || [ "$new_port" -lt 1 ] || [ "$new_port" -gt 65535 ]; then
+      echo -e "${RED}Invalid port: ${new_port}. Please enter a port number between 1 and 65535.${RESET}"
+      wait_for_key
+      return
+   fi
+   echo
+
+   # Check if the new port is the same as the old port
+   if [ "$new_port" -eq "$port" ]; then
+      echo -e "${RED}The new port is the same as the old port.${RESET}"
+      wait_for_key
+      return
+   fi
+
+   # Save the reverse proxy configuration
+   echo -e "${DIM}Saving reverse proxy configuration...${RESET}"
+   reverse_proxy_save_config "$domain" "$new_port"
+
+   # Reload Nginx
+   echo -e "${DIM}Reloading Nginx...${RESET}"
+   systemctl reload nginx
+
+   # Reload the reverse proxy configurations
+   echo -e "${DIM}Reloading reverse proxy configurations...${RESET}"
+   reverse_proxy_load_configs &>/dev/null
+
+   # Rebuild the menu
+   echo -e "${DIM}Updating menu...${RESET}"
+   update_menu "reverse_proxy"
+
+   echo
+   echo -e "${GREEN}Reverse proxy configuration updated.${RESET}"
+
+   wait_for_key
+}
+
+task_delete_reverse_proxy() {
+   local domain=$1
+   local port=${domains_and_ports[$domain]}
+
+   clear
+
+   echo -e "${DIM}Delete reverse proxy configuration for ${domain}${RESET}"
+
+   # Ask for confirmation
+   echo
+   read -p "Are you sure you want to delete the reverse proxy configuration? [y/N] " -n 1 -r
+   echo
+
+   echo
+   if [[ $REPLY =~ ^[Yy]$ ]]; then
+      # Delete the Nginx configuration file
+      echo -e "${DIM}Deleting Nginx configuration file...${RESET}"
+      rm -f "${settings["NGINX_CONFIG_DIR"]}/${domain}.conf"
+
+      # Reload Nginx
+      echo -e "${DIM}Reloading Nginx...${RESET}"
+      systemctl reload nginx
+
+      # Reload the reverse proxy configurations
+      echo -e "${DIM}Reloading reverse proxy configurations...${RESET}"
+      reverse_proxy_load_configs &>/dev/null
+
+      # TODO: Remove from cache
+
+      # Rebuild the menu
+      echo -e "${DIM}Updating menu...${RESET}"
+      update_menu "reverse_proxy"
+
+      echo
+      echo -e "${GREEN}Reverse proxy configuration deleted.${RESET}"
+   else
+      echo -e "${RED}Operation canceled.${RESET}"
+      # Play a beep sound
+      echo -e -n "$BEEP"
+   fi
+
+   wait_for_key
+}
+
+# Display the information of a specific settings key
+task_inspect_settings_key() {
+   local key=$1
+   local value=${settings[$key]}
+   local default_value=${default_settings[$key]}
+
+   clear
+
+   # Display key information
+   settings_display_key_info "$key"
+
+   wait_for_key
+}
+
+# Modify a specific settings key
+task_modify_settings_key() {
+   local key=$1
+   local value=${settings[$key]}
+
+   clear
+
+   # Display key information
+   echo -e -n "$DIM"
+   settings_display_key_info "$key"
+   echo -e -n "$RESET"
+
+   # Ask for new value
+   echo
+   read -p -r "Enter new value: " new_value
+
+   # Ask for confirmation
+   echo
+   echo -e "Current value: ${value}"
+   echo -e "New value: ${new_value}"
+   echo
+   read -p "Are you sure you want to update the setting? [y/N] " -n 1 -r
+
+   echo
+   if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+      echo -e "${RED}Operation canceled.${RESET}"
+      # Play a beep sound
+      echo -e -n "$BEEP"
+      wait_for_key
+      return
+   else
+      # Update the settings key value
+      settings[$key]=$new_value
+      settings_save
+      echo -e "${GREEN}Setting updated.${RESET}"
+   fi
+
+   wait_for_key
+}
+
+# Restore default value of a specific settings key
+task_restore_default_settings_key() {
+   local key=$1
+   local value=${settings[$key]}
+   local default_value=${default_settings[$key]}
+
+   clear
+
+   # Display key information
+   echo -e -n "$DIM"
+   settings_display_key_info "$key"
+   echo -e -n "$RESET"
+
+   # Ask for confirmation
+   echo
+   read -p "Are you sure you want to restore the default value? [y/N] " -n 1 -r
+
+   echo
+   if [[ $REPLY =~ ^[Yy]$ ]]; then
+      settings[$key]=$default_value
+      settings_save
+      echo -e "${GREEN}Default value restored.${RESET}"
+   else
+      echo -e "${RED}Operation canceled.${RESET}"
+      # Play a beep sound
+      echo -e -n "$BEEP"
+   fi
+
+   wait_for_key
+}
+
+# ===== Menu Builders =============================================================================
+
+# Display the main menu
+build_menu_main() {
+   menu_header="Main Menu"
+   menu=(
+      "${RED}Exit${RESET}" "exit 0"
+      "Manage reverse proxies" "build_menu_reverse_proxy"
+      "${DIM}Edit settings${RESET}" "build_menu_settings"
+   )
+}
+
+# Display the reverse proxy menu
+build_menu_reverse_proxy() {
+   # If has second argument, build menu for specific reverse proxy
+   if [ -n "$1" ]; then
+      menu_header="Edit Reverse Proxy"
+      menu=(
+         "${RED}Back${RESET}" "build_menu_reverse_proxy"
+         "${YELLOW}Modify${RESET}" "task_modify_reverse_proxy $1"
+         "${RED}Delete${RESET}" "task_delete_reverse_proxy $1"
+      )
+      return
+   else
+      # Otherwise, build menu for all reverse proxies
+      menu_header="Reverse Proxy Manager"
+      menu=(
+         "${RED}Back${RESET}" "build_menu_main"
+         "${GREEN}Add new reverse proxy${RESET}" "task_add_reverse_proxy"
+      )
+
+      # Load reverse proxy configurations
+      reverse_proxy_load_configs &>/dev/null
+
+      # Add reverse proxy configurations to the menu
+      for domain in "${!domains_and_ports[@]}"; do
+         menu+=("${domain} ${INVERSE_OFF}${DIM}(port: ${domains_and_ports[$domain]})${RESET}" "build_menu_reverse_proxy $domain")
+      done
+   fi
+}
+
+# Display the settings menu
+build_menu_settings() {
+   # If has argument, build menu for specific setting
+   if [ -n "$1" ]; then
+      menu_header="Edit Setting"
+      menu=(
+         "${RED}Back${RESET}" "build_menu_settings"
+         "${CYAN}Inspect${RESET}" "task_inspect_settings_key $1"
+         "${YELLOW}Modify${RESET}" "task_modify_settings_key $1"
+         "${RED}Restore default${RESET}" "task_restore_default_settings_key $1"
+      )
+      return
+   else
+      # Otherwise, build menu for all settings
+      menu_header="Settings"
+      menu=(
+         "${DIM}Back${RESET}" "build_menu_main"
+      )
+      # Add settings to the menu
+      for key in "${!settings[@]}"; do
+         menu+=("${key}${INVERSE_OFF} ${DIM}(current: ${settings[$key]})${RESET}" "build_menu_settings $key")
+      done
+   fi
+}
 
 # ===== Main ======================================================================================
+
+# Default settings
+declare -A default_settings
+default_settings["NGINX_CONFIG_DIR"]="/etc/nginx/conf.d"
+for key in "${!default_settings[@]}"; do
+   settings[$key]="${default_settings[$key]}"
+done
+
+# Load settings
+settings_load
+
+# Build the main menu
+build_menu_main
+
+# Run the menu
+menu_start
